### ISSUE TITLE
Is there anyway to capture the link itself?

### ISSUE THREAD

**Issue by kadnan** [schasins/helena#11]
I could not find the way. I want to capture the title and the link itself from CraigsList.

**Comment by schasins** [comment]
See https://github.com/schasins/helena/issues/8 .  Any ideas about where to document this?

**Comment by kadnan** [comment]
Looks good though I have yet to try it out. You can make a video or include on the example page because this is the very basic requirement.

**Comment by schasins** [comment]
Now documented at [http://helena-lang.org/demonstration#collectingLinkCells](http://helena-lang.org/demonstration#collectingLinkCells) and [http://helena-lang.org/using-helena-ui#collectLinks](http://helena-lang.org/using-helena-ui#collectLinks).
