### ISSUE TITLE
scroll function block

### ISSUE THREAD

**Issue by vitordino** [schasins/helena#14]
Hi schasins,

first of all congratulations on this really nice project 🎉 

i'm just struggling with one thing: virtualized lists. I think the simples way to circunvent this is:

1. `scrap` what is visible
2. `scroll` the viewport (or configurable) height
3. do it again

(probably the scoll block it's better to be coded outside the main scrap block)

example: [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List)

so, for this workflow, i would need a `scroll` or `scrollTo` function block.. what do you think?

**Comment by schasins** [comment]
Great question!  I suspect that we actually already have support for what you're trying to do.  Have you taken a look at the directions for editing tables: http://helena-lang.org/using-helena-ui#editTable ?  Those directions tell you how to tell Helena to do a scroll-for-more interaction to reach more rows of a list.

**Comment by vitordino** [comment]
sorry, probably missed this part 😅 

i'll take a closer look, if it fits me, i'll close this 😀

**Comment by vitordino** [comment]
couldn't make it work, but didn't read the full documentation..

i'm closing this until I have more time on this.. thanks for your fast reply (:
