### ISSUE TITLE
How can I execute pagination?

### ISSUE THREAD

**Issue by kadnan** [schasins/helena#15]
I want to go one page after the other. Right now I do the following(an example is CraigsList)

- ALT+CLICK listing text
- Click on NEXT>> link 
- GO TO Step 1

What it does that it keeps moving between page 1 - page2 in an infinite loop

**Comment by schasins** [comment]
[http://helena-lang.org/using-helena-ui#editTable](http://helena-lang.org/using-helena-ui#editTable)
