### ISSUE TITLE
When I click "Download Script" button, nothing happens

### ISSUE THREAD

**Issue by kadnan** [schasins/helena#20]
Could not attached the screen. Anyways, when I hit the Download script button it does nothing.

**Comment by schasins** [comment]
I can't reproduce this issue.  Can you give me any additional information?

**Comment by kadnan** [comment]
I assume that when I hit _Download Script_ button I will be able to save script content locally.

<img width="952" alt="screen shot 2019-02-11 at 12 02 25 am" src="https://user-images.githubusercontent.com/273196/52538124-9a5f7b00-2d90-11e9-8cc0-520932496903.png">

**Comment by schasins** [comment]
Looks like Chrome has an issue with downloading very large files this way.  I've updated with a workaround.  You'll have to pull from both repositories to get the update.

**Comment by kadnan** [comment]
@schasins I did not notice your response.  Do I have to pull `helena/` repo only or the module as well?

**Comment by schasins** [comment]
The module also.
