### ISSUE TITLE
Default Helena server timing out?

### ISSUE THREAD

**Issue by jlumbroso** [schasins/helena#23]
The extension runs smoothly the overwhelming part of the time. Occasionally it stalls, and when looking at the output of the developer console, it appears that the server `kaofang.cs.berkeley.edu:8080` times out arbitrarily:

<img width="752" alt="Screen Shot 2019-04-27 at 1 46 46 PM" src="https://user-images.githubusercontent.com/11770469/56853235-fac37a80-68f2-11e9-820e-d747690dde7a.png">

From my understanding, `kaofang` is currently the place where a default instance of the Helena Server is running, for purposes of simplifying the installation of the Helena extension. I am guessing that perhaps the server is overwhelmed by traffic. If this is correct, I can think of two suggestions to improve this issue:

1. Error reporting to the user, to explain the temporary problem. (I think otherwise, such interactions risk undermining the trust of the non-CS users of this system.)

2. I wonder if it would make sense to transition the Helena server to a serverless type of instance, so that it would scale exactly based with demand.

**Comment by schasins** [comment]
I know we're talking about this via other channels, but just in case anyone else runs across this issue...this results from running an old version of the Chrome extension that's still pointed at an old server.  We've since upgraded to a new AWS setup.  Getting the latest version of the extension should fix this!  :)

**Comment by jlumbroso** [comment]
Created this pull request to address the problem (an outdated submodule):
https://github.com/schasins/helena/pull/24

**Comment by schasins** [comment]
Nice catch!  I should have thought of this!
