### ISSUE TITLE
Is the server down?

### ISSUE THREAD

**Issue by kadnan** [schasins/helena#27]
I am getting the following.

<img width="1264" alt="Screen Shot 2019-05-11 at 11 02 12 AM" src="https://user-images.githubusercontent.com/273196/57565749-84d40e80-73dc-11e9-9c05-ec530d8ab03c.png">

**Comment by schasins** [comment]
Have you been able to recreate this, intentionally or accidentally?  When I checked at the time, the server was up and operating normally, but I never had a chance to check if anything else might be causing issues, so I guessed it was a slow connection issue on your end?

**Comment by kadnan** [comment]
my net speed is perfect. The other server URL is opening fine.

**Comment by schasins** [comment]
Oh, got it!  You're trying to use the deprecated server.  We've fully switched over from kaofang.cs.berkeley.edu to the new AWS server at this point, so you'll have to update your version of Helena and use the new one.
