### ISSUE TITLE
Cannot seem to run from source

### ISSUE THREAD

**Issue by mdittmer** [schasins/helena#39]
I tried running Helena from source today. Here's what I did:

- Install fresh Chromium (Linux) build from https://download-chromium.appspot.com/

- Download `helena` and `helena-lang`, and place `helena-lang` inside `helena`:

```sh
$ git clone git@github.com:schasins/helena.git
$ git clone git@github.com:schasins/helena-lang.git
$ cd helena/src/scripts/lib
$ rmdir helena-library
$ ln -s ../../../../helena-lang helena-library
```
- Add `helena/src` as an unpacked extension to Chromium in developer mode

- Launch Helena

I observed two overarching issues:

- Something is wrong with plumbing events to/from pages: no preview shows up when I hold down `Ctrl`+`Alt`, and nothing happens in the extension when I `Ctrl`+`Alt`+`<click>`

- The "Stop Recording" button does not work, but the "Cancel Recording" button does work; console error from pressing "Stop Recording":

```
Uncaught TypeError: Cannot read property 'outerWidth' of undefined
    at setWindowSize (mainpanel_script.js:129)
    at HTMLDivElement._stopRecording (mainpanel_script.js:153)
    at HTMLDivElement.dispatch (jquery.js:3)
    at HTMLDivElement.r.handle (jquery.js:3)
```

Are there specific revisions or branches I should use if I want to develop with Helena?

**Comment by mdittmer** [comment]
Additional context: I installed fresh Chromium because I was concerned that the configuration of my existing Chrome installation might have been interfering with Helena. I got the same results using my day-to-day installation of Chrome.

**Comment by schasins** [comment]
Hi!  I can't seem to reproduce this.  I just tried a fresh install following the directions here: https://github.com/schasins/helena/wiki/Installing-Helena-(for-Developers) without issues.  It's possible this is an issue with Linux Chrome, but I think the first step is to try installing via `git clone --recursive https://github.com/schasins/helena.git` instead of the sequence of downloads you described.  Let me know how it goes!

**Comment by mdittmer** [comment]
Ah, yes. It seems to be working now. Using `--recursive` did the trick. Thanks!
