### ISSUE TITLE
Add Firefox Support

### ISSUE THREAD

**Issue by sohang3112** [schasins/helena#41]
First of all, this is a quite useful browser extension - thanks for making it!

### Feature Request
As I frequently use Firefox, it would be good if this project could also be ported to Firefox. Do you think this could be feasible?

According to [this article](https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/), porting a Chrome extension to Firefox is generally not very hard.

**Comment by schasins** [comment]
Thank you so much for reaching out about this!  Unfortunately no one on the team has the bandwidth to work on this, but please feel free to send a pull request if you do it yourself!
