### ISSUE TITLE
Can I use it remotely?

### ISSUE THREAD

**Issue by kadnan** [schasins/helena#9]
Is it possible to use it on remote AWS machines? I recently used `ROUSILLON` and loved it. However I want to automate the process on the remote machine. How can I do it?

**Comment by schasins** [comment]
Definitely!  I've used it from AWS myself.  There are some utility scripts available here https://github.com/schasins/helena/tree/master/utilities that might be helpful to you.  Especially runOnAllEC2 and runHelenaScriptInParallel.  But for now those are really just scripts that I've thrown together for various quick tasks, so it's not really easy to get up and running with them.  We're currently looking at putting together a Docker image, so stay tuned if that would be an easier method for you.

**Comment by schasins** [comment]
Here's the docker image I promised: https://github.com/schasins/helena-docker  Let me know if there's anything about it that needs additional documentation.  Here are the basics:
(1) If not yet installed, install docker: https://www.docker.com/get-started
(2) Download the image tar, for example: wget https://github.com/schasins/helena-docker/raw/master/helena-image.tar
(3) Run the load command to load the tar: docker load --input helena-image.tar
(4) Start the program with the run command, for example: docker run -t -p 5900:5900 -e VNC_SERVER_PASSWORD=password -e HELENA_PROGRAM_ID=2357 -e NUM_PARALLEL_WORKERS=1 -e TIME_LIMIT_IN_HOURS=23 -e NUM_RUNS_ALLOWED_PER_WORKER=1 --user apps --privileged local/chrome:0.0.1

**Comment by kadnan** [comment]
wow!
Yes, I do use Docker. I will give it a try once get done with my work.

Thanks !
